import { normalizeText } from './format'

export const PRODUCT_SEEDS = [
  { name: 'Cheese Bacon', category: 'Hambúrgueres', price: 22, source: 'Cardápio' },
  { name: 'Flag Ship', category: 'Hambúrgueres', price: 27, source: 'Cardápio' },
  { name: 'Cheddar Bacon', category: 'Hambúrgueres', price: 29, source: 'Cardápio' },
  { name: 'Crazy Burger', category: 'Hambúrgueres', price: 32, source: 'Cardápio' },
  { name: 'Big Dream', category: 'Hambúrgueres', price: 37, source: 'Cardápio' },
  { name: 'Speed Max', category: 'Hambúrgueres', price: 43, source: 'Cardápio' },
  { name: 'Cebóra', category: 'Hambúrgueres', price: 32, source: 'Cardápio' },
  { name: 'Costeletion', category: 'Hambúrgueres', price: 32, source: 'Cardápio' },
  { name: 'Pepeburger', category: 'Hambúrgueres', price: 25, source: 'Cardápio' },
  { name: 'Ultra Speed', category: 'Hambúrgueres', price: 22, source: 'Cardápio' },
  { name: 'Turbo Ultra Speed', category: 'Hambúrgueres', price: 32, source: 'Cardápio' },
  { name: 'Speed Burger', category: 'Fast Food', price: 20, source: 'Cardápio' },
  { name: 'Speed Chicken', category: 'Fast Food', price: 20, source: 'Cardápio' },
  { name: 'Speed Duplo', category: 'Fast Food', price: 30, source: 'Cardápio' },
  { name: 'Speed Simples', category: 'Fast Food', price: 20, source: 'Cardápio' },
  { name: 'Honey Burger', category: 'Hambúrgueres', price: 40, source: 'Cardápio' },
  { name: 'Flag Triplo', category: 'Hambúrgueres', price: 43, source: 'Cardápio' },
  { name: 'Cheddar Cremoso C/Bacon', category: 'Hambúrgueres', price: 37, source: 'Cardápio' },
  { name: 'Flagship+ Fritas Individual+ Coca Lata', category: 'Combos', price: 39.9, source: 'Cardápio' },
  { name: 'Big Dream + Fritas Individual + Coca Lata', category: 'Combos', price: 49.9, source: 'Cardápio' },
  { name: 'Cheddar Bacon + Fritas Individual + Coca Lata', category: 'Combos', price: 40.9, source: 'Cardápio' },
  { name: 'Speed Burger + Coca 350 Ml + Batata Individual', category: 'Combos Fast Food', price: 35.9, source: 'Cardápio' },
  { name: 'Speed Chicken + Coca 350 Ml + Batata Individual', category: 'Combos Fast Food', price: 33.9, source: 'Cardápio' },
  { name: 'Speed Duplo+ Coca 350 Ml + Batata Individual', category: 'Combos Fast Food', price: 47.9, source: 'Cardápio' },
  { name: 'Speed Simples + Coca 350 Ml + Batata Individual', category: 'Combos Fast Food', price: 34.9, source: 'Cardápio' },
  { name: 'Fritas Individual + Coca Lata 350 Ml', category: 'Porções', price: 12.9, source: 'Cardápio' },
  { name: 'Batata Frita Meia', category: 'Porções', price: 18, source: 'Cardápio' },
  { name: 'Batata Frita Inteira', category: 'Porções', price: 22, source: 'Cardápio' },
  { name: 'Batata Frita C/ Cheddar Cremoso E Bacon Meia', category: 'Porções', price: 24, source: 'Cardápio' },
  { name: 'Batata Frita C/ Cheddar Cremoso E Bacon Inteira', category: 'Porções', price: 32.9, source: 'Cardápio' },
  { name: 'Cebola Empanada', category: 'Porções', price: 26, source: 'Cardápio' },
  { name: 'Potinho Cheddar Cremoso C/Bacon', category: 'Complementos', price: 8.9, source: 'Cardápio' },
  { name: 'Mini Churros', category: 'Complementos', price: 8.9, source: 'Cardápio' },
  { name: 'Nuggets', category: 'Complementos', price: 12.9, source: 'Cardápio' },
  { name: 'Coca Cola 350Ml', category: 'Bebidas', price: 6, source: 'Cardápio' },
  { name: 'Sprite 350Ml', category: 'Bebidas', price: 6, source: 'Cardápio' },
  { name: 'Coca Cola 2L', category: 'Bebidas', price: 15, source: 'Cardápio' },
  { name: 'Jaboti Guaraná 2L', category: 'Bebidas', price: 8, source: 'Cardápio' },
  { name: 'Água mineral sem Gás ou com Gás', category: 'Bebidas', price: 4, source: 'Cardápio' },
  { name: 'Schweppes 350ml', category: 'Bebidas', price: 6, source: 'Cardápio' },
]

export const INGREDIENT_SEEDS = [
  { name: 'Carne moída', category: 'Carnes', unit: 'kg', stock_qty: 12, min_qty: 6, cost_per_unit: 38 },
  { name: 'Pão brioche', category: 'Pães', unit: 'un', stock_qty: 120, min_qty: 50, cost_per_unit: 1.45 },
  { name: 'Pão fast food', category: 'Pães', unit: 'un', stock_qty: 90, min_qty: 40, cost_per_unit: 1.1 },
  { name: 'Queijo cheddar', category: 'Laticínios', unit: 'fatia', stock_qty: 220, min_qty: 80, cost_per_unit: 0.85 },
  { name: 'Queijo mussarela empanado', category: 'Laticínios', unit: 'un', stock_qty: 24, min_qty: 8, cost_per_unit: 4.8 },
  { name: 'Bacon', category: 'Carnes', unit: 'g', stock_qty: 8000, min_qty: 2500, cost_per_unit: 0.045 },
  { name: 'Calabresa defumada', category: 'Carnes', unit: 'g', stock_qty: 3000, min_qty: 1000, cost_per_unit: 0.028 },
  { name: 'Costela desfiada', category: 'Carnes', unit: 'g', stock_qty: 4000, min_qty: 1500, cost_per_unit: 0.055 },
  { name: 'Frango empanado', category: 'Carnes', unit: 'un', stock_qty: 40, min_qty: 12, cost_per_unit: 3.9 },
  { name: 'Alface', category: 'Hortifruti', unit: 'g', stock_qty: 1500, min_qty: 600, cost_per_unit: 0.009 },
  { name: 'Tomate', category: 'Hortifruti', unit: 'g', stock_qty: 3000, min_qty: 1000, cost_per_unit: 0.012 },
  { name: 'Cebola roxa', category: 'Hortifruti', unit: 'g', stock_qty: 1800, min_qty: 700, cost_per_unit: 0.008 },
  { name: 'Cebola empanada', category: 'Hortifruti', unit: 'g', stock_qty: 3000, min_qty: 1200, cost_per_unit: 0.018 },
  { name: 'Picles', category: 'Hortifruti', unit: 'g', stock_qty: 1000, min_qty: 300, cost_per_unit: 0.02 },
  { name: 'Rúcula', category: 'Hortifruti', unit: 'g', stock_qty: 800, min_qty: 300, cost_per_unit: 0.015 },
  { name: 'Doritos', category: 'Mercearia', unit: 'g', stock_qty: 1500, min_qty: 500, cost_per_unit: 0.025 },
  { name: 'Requeijão cremoso', category: 'Laticínios', unit: 'g', stock_qty: 3000, min_qty: 1000, cost_per_unit: 0.022 },
  { name: 'Molho especial', category: 'Molhos', unit: 'g', stock_qty: 3000, min_qty: 1000, cost_per_unit: 0.015 },
  { name: 'Molho Billy Jack', category: 'Molhos', unit: 'g', stock_qty: 2200, min_qty: 700, cost_per_unit: 0.017 },
  { name: 'Baconaise', category: 'Molhos', unit: 'g', stock_qty: 2200, min_qty: 700, cost_per_unit: 0.016 },
  { name: 'Barbecue', category: 'Molhos', unit: 'g', stock_qty: 2200, min_qty: 700, cost_per_unit: 0.017 },
  { name: 'Ketchup', category: 'Molhos', unit: 'g', stock_qty: 2200, min_qty: 700, cost_per_unit: 0.012 },
  { name: 'Mostarda', category: 'Molhos', unit: 'g', stock_qty: 1800, min_qty: 600, cost_per_unit: 0.012 },
  { name: 'Batata frita', category: 'Congelados', unit: 'g', stock_qty: 12000, min_qty: 4000, cost_per_unit: 0.013 },
  { name: 'Cheddar cremoso', category: 'Laticínios', unit: 'g', stock_qty: 3000, min_qty: 1000, cost_per_unit: 0.024 },
  { name: 'Coca Cola 350ml', category: 'Bebidas', unit: 'un', stock_qty: 48, min_qty: 12, cost_per_unit: 4.1 },
  { name: 'Sprite 350ml', category: 'Bebidas', unit: 'un', stock_qty: 24, min_qty: 8, cost_per_unit: 3.9 },
  { name: 'Coca Cola 2L', category: 'Bebidas', unit: 'un', stock_qty: 14, min_qty: 6, cost_per_unit: 10.5 },
  { name: 'Jaboti Guaraná 2L', category: 'Bebidas', unit: 'un', stock_qty: 12, min_qty: 4, cost_per_unit: 5.5 },
  { name: 'Água mineral', category: 'Bebidas', unit: 'un', stock_qty: 30, min_qty: 10, cost_per_unit: 2.1 },
  { name: 'Embalagem burger', category: 'Embalagens', unit: 'un', stock_qty: 180, min_qty: 60, cost_per_unit: 0.75 },
  { name: 'Embalagem porção', category: 'Embalagens', unit: 'un', stock_qty: 60, min_qty: 20, cost_per_unit: 1.1 },
  { name: 'Embalagem bebida', category: 'Embalagens', unit: 'un', stock_qty: 60, min_qty: 20, cost_per_unit: 0.4 },
]

const recipe = (productName, lines) => ({
  productName,
  lines,
})

export const RECIPE_SEEDS = [
  recipe('Cheese Bacon', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Bacon', 30],
    ['Molho especial', 20],
    ['Embalagem burger', 1],
  ]),
  recipe('Flag Ship', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Alface', 15],
    ['Tomate', 20],
    ['Cebola roxa', 10],
    ['Bacon', 25],
    ['Molho Billy Jack', 18],
    ['Embalagem burger', 1],
  ]),
  recipe('Cheddar Bacon', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Bacon', 25],
    ['Cebola roxa', 10],
    ['Baconaise', 20],
    ['Embalagem burger', 1],
  ]),
  recipe('Crazy Burger', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Requeijão cremoso', 25],
    ['Bacon', 25],
    ['Doritos', 18],
    ['Picles', 10],
    ['Alface', 15],
    ['Tomate', 20],
    ['Cebola roxa', 10],
    ['Barbecue', 20],
    ['Embalagem burger', 1],
  ]),
  recipe('Big Dream', [
    ['Carne moída', 0.24],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Bacon', 25],
    ['Cebola roxa', 10],
    ['Baconaise', 20],
    ['Barbecue', 18],
    ['Embalagem burger', 1],
  ]),
  recipe('Speed Max', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo mussarela empanado', 1],
    ['Queijo cheddar', 2],
    ['Bacon', 25],
    ['Barbecue', 20],
    ['Rúcula', 12],
    ['Tomate', 20],
    ['Cebola roxa', 10],
    ['Embalagem burger', 1],
  ]),
  recipe('Cebóra', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Cebola empanada', 40],
    ['Requeijão cremoso', 25],
    ['Queijo cheddar', 2],
    ['Alface', 15],
    ['Bacon', 25],
    ['Barbecue', 18],
    ['Embalagem burger', 1],
  ]),
  recipe('Costeletion', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Requeijão cremoso', 25],
    ['Costela desfiada', 70],
    ['Queijo cheddar', 2],
    ['Mostarda', 10],
    ['Barbecue', 18],
    ['Embalagem burger', 1],
  ]),
  recipe('Pepeburger', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Requeijão cremoso', 25],
    ['Calabresa defumada', 35],
    ['Embalagem burger', 1],
  ]),
  recipe('Ultra Speed', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 1],
    ['Picles', 10],
    ['Cebola roxa', 10],
    ['Ketchup', 15],
    ['Embalagem burger', 1],
  ]),
  recipe('Turbo Ultra Speed', [
    ['Carne moída', 0.24],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Picles', 10],
    ['Cebola roxa', 10],
    ['Ketchup', 15],
    ['Embalagem burger', 1],
  ]),
  recipe('Speed Burger', [
    ['Carne moída', 0.12],
    ['Pão fast food', 1],
    ['Cebola roxa', 8],
    ['Alface', 12],
    ['Ketchup', 10],
    ['Mostarda', 8],
    ['Queijo cheddar', 1],
    ['Embalagem burger', 1],
  ]),
  recipe('Speed Chicken', [
    ['Frango empanado', 1],
    ['Pão fast food', 1],
    ['Cebola roxa', 8],
    ['Alface', 12],
    ['Ketchup', 10],
    ['Mostarda', 8],
    ['Embalagem burger', 1],
  ]),
  recipe('Speed Duplo', [
    ['Carne moída', 0.24],
    ['Pão fast food', 1],
    ['Cebola roxa', 8],
    ['Alface', 12],
    ['Ketchup', 10],
    ['Mostarda', 8],
    ['Queijo cheddar', 1],
    ['Embalagem burger', 1],
  ]),
  recipe('Speed Simples', [
    ['Carne moída', 0.12],
    ['Pão fast food', 1],
    ['Ketchup', 10],
    ['Mostarda', 8],
    ['Queijo cheddar', 1],
    ['Embalagem burger', 1],
  ]),
  recipe('Honey Burger', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 1],
    ['Bacon', 25],
    ['Rúcula', 12],
    ['Embalagem burger', 1],
  ]),
  recipe('Flag Triplo', [
    ['Carne moída', 0.36],
    ['Pão brioche', 1],
    ['Queijo cheddar', 3],
    ['Alface', 18],
    ['Tomate', 25],
    ['Cebola roxa', 12],
    ['Bacon', 30],
    ['Molho Billy Jack', 20],
    ['Embalagem burger', 1],
  ]),
  recipe('Cheddar Cremoso C/Bacon', [
    ['Carne moída', 0.12],
    ['Pão brioche', 1],
    ['Queijo cheddar', 2],
    ['Cheddar cremoso', 35],
    ['Bacon', 25],
    ['Embalagem burger', 1],
  ]),
  recipe('Fritas Individual + Coca Lata 350 Ml', [
    ['Batata frita', 120],
    ['Coca Cola 350ml', 1],
    ['Embalagem porção', 1],
  ]),
  recipe('Batata Frita Meia', [
    ['Batata frita', 250],
    ['Embalagem porção', 1],
  ]),
  recipe('Batata Frita Inteira', [
    ['Batata frita', 500],
    ['Embalagem porção', 1],
  ]),
  recipe('Batata Frita C/ Cheddar Cremoso E Bacon Meia', [
    ['Batata frita', 250],
    ['Cheddar cremoso', 60],
    ['Bacon', 35],
    ['Embalagem porção', 1],
  ]),
  recipe('Batata Frita C/ Cheddar Cremoso E Bacon Inteira', [
    ['Batata frita', 500],
    ['Cheddar cremoso', 120],
    ['Bacon', 60],
    ['Embalagem porção', 1],
  ]),
  recipe('Cebola Empanada', [
    ['Cebola empanada', 180],
    ['Embalagem porção', 1],
  ]),
  recipe('Potinho Cheddar Cremoso C/Bacon', [
    ['Cheddar cremoso', 100],
    ['Bacon', 25],
    ['Embalagem porção', 1],
  ]),
  recipe('Nuggets', [
    ['Frango empanado', 6],
    ['Embalagem porção', 1],
  ]),
  recipe('Coca Cola 350Ml', [['Coca Cola 350ml', 1], ['Embalagem bebida', 1]]),
  recipe('Sprite 350Ml', [['Sprite 350ml', 1], ['Embalagem bebida', 1]]),
  recipe('Coca Cola 2L', [['Coca Cola 2L', 1], ['Embalagem bebida', 1]]),
  recipe('Jaboti Guaraná 2L', [['Jaboti Guaraná 2L', 1], ['Embalagem bebida', 1]]),
  recipe('Água mineral sem Gás ou com Gás', [['Água mineral', 1], ['Embalagem bebida', 1]]),
]

export const SUPPLIER_CATEGORY_OPTIONS = [
  'Carnes',
  'Pães',
  'Bebidas',
  'Laticínios',
  'Hortifruti',
  'Molhos',
  'Embalagens',
  'Mercearia',
  'Congelados',
  'Diversos',
]

export function withNorm(list) {
  return list.map((item) => ({ ...item, normalized_name: normalizeText(item.name || item.nome) }))
}
